version: "3"

services:
  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - ./data:/var/lib/mysql
    - ./logs/mysql:/var/log/mysql
    networks:
      - gear5_network

  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: ${PROJECT_NAME}_mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - gear5_network

  wordpress:
    container_name: ${PROJECT_NAME}_wordpress
    image: wordpress:latest
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: ${PROJECT_NAME}_mysql:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
    - ./www:/var/www/html
    - ./logs/wordpress:/var/log/apache2
    networks:
      - gear5_network

networks:
  gear5_network:
    driver: bridge





